#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Validate branch name
local_branch_name="$(git rev-parse --abbrev-ref HEAD)"
recommend_branch_name_regexp='^((chore|feat|fix|hotfix|imp)\/[a-zA-Z0-9\-]+)$'

if [[ ! $local_branch_name =~ $recommend_branch_name ]]; then
    message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: $recommend_branch_name_regexp. Your commit will be rejected. You should rename your branch to a valid name and try again."

    echo $message
    exit 1
fi


npx --no-install commitlint --edit "$1"
